import React, { useState, useEffect } from 'react';
import { Clock, User, AlertCircle, X, GitMerge, GitBranch, GitCommit, GitPullRequest, CheckCircle, Circle, Loader2, FileText } from 'lucide-react';

const TaskCard = ({ task, onStatusChange }) => {
  const [showDetails, setShowDetails] = useState(false);

  const getRiskColor = (score) => {
    if (score > 70) return '#de350b'; // High Risk
    if (score > 40) return '#ffab00'; // Medium Risk
    return '#00875a'; // Low Risk
  };

  const riskColor = getRiskColor(task.risk_score);

  // Helper to stop propagation for inline buttons
  const [githubCommits, setGithubCommits] = useState([]);
  const [loadingGithub, setLoadingGithub] = useState(false);

  useEffect(() => {
    if (showDetails && task.status !== 'To Do') {
      const fetchCommits = async () => {
        setLoadingGithub(true);
        try {
          const res = await fetch(`http://localhost:5000/api/github/commits?repo=facebook/react`);
          const data = await res.json();
          if (data.status === 'success') {
            setGithubCommits(data.commits);
          }
        } catch (err) { console.error(err); }
        setLoadingGithub(false);
      };
      fetchCommits();
    }
  }, [showDetails, task.status]);

  const handleStatusChange = (e, status) => {
    e.stopPropagation();
    onStatusChange(task.id, status);
  };

  const handleDownloadReport = () => {
    const reportContent = `
========================================
       AI TASK FLOW REPORT
========================================
Task ID: ${task.id}
Title: ${task.title}
Status: ${task.status}
Risk: ${task.risk_score > 70 ? 'High' : task.risk_score > 40 ? 'Medium' : 'Low'} (${task.risk_score}%)
Assignee: ${task.assignee || 'Unassigned'}
Deadline: ${task.deadline_days} days

--- DESCRIPTION ---
${task.description || 'No detailed description provided.'}

--- CI/CD PIPELINE STATUS ---
${task.status === 'Done' ? 'Deployed to Production successfully.' : task.status === 'In Progress' ? 'Currently Pipeline is running (Tests & QA in progress).' : 'No active branches.'}

--- TEAM ALLOCATION ---
Primary Assignee: ${task.assignee || 'Team Lead'} (${task.status === 'Done' ? '100' : task.status === 'In Progress' ? '65' : '0'}%)
System Review: Architecture Team (${task.status === 'Done' ? '100' : task.status === 'In Progress' ? '40' : '0'}%)

Generated by Virtual-Decision-System AI
========================================
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Task_Flow_Report_${task.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <>
    <div className="card task-card" style={{ 
      padding: '1rem', 
      marginBottom: '0.75rem', 
      borderLeft: `4px solid ${riskColor}`,
      cursor: 'pointer',
      transition: 'transform 0.2s, box-shadow 0.2s'
    }}
    onClick={() => setShowDetails(true)}
    onMouseEnter={(e) => {
      e.currentTarget.style.transform = 'translateY(-2px)';
      e.currentTarget.style.boxShadow = '0 4px 12px rgba(0,0,0,0.1)';
    }}
    onMouseLeave={(e) => {
      e.currentTarget.style.transform = 'translateY(0)';
      e.currentTarget.style.boxShadow = '0 1px 3px rgba(0,0,0,0.1)';
    }}
    >
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.5rem' }}>
        <h4 style={{ margin: 0, fontSize: '0.95rem', fontWeight: 600, color: '#172b4d' }}>{task.title}</h4>
        <div style={{ 
          display: 'flex', 
          alignItems: 'center', 
          gap: '0.25rem', 
          fontSize: '0.7rem', 
          fontWeight: 700, 
          color: riskColor,
          textTransform: 'uppercase',
          background: `${riskColor}15`,
          padding: '2px 6px',
          borderRadius: '3px'
        }}>
          <AlertCircle size={10} />
          {task.risk_score > 70 ? 'High Risk' : task.risk_score > 40 ? 'Med Risk' : 'Low Risk'}
        </div>
      </div>
      
      <div style={{ position: 'relative', marginBottom: '1rem' }}>
        <p style={{ 
          fontSize: '0.85rem', 
          color: '#5e6c84', 
          margin: 0, 
          lineBreak: 'anywhere',
          display: '-webkit-box', 
          WebkitLineClamp: 3, 
          WebkitBoxOrient: 'vertical', 
          overflow: 'hidden'
        }}>
          {task.description || 'No description provided.'}
        </p>
      </div>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.8rem', color: '#5e6c84' }}>
          <User size={14} />
          <span>{task.assignee || 'Unassigned'}</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.8rem', color: '#5e6c84' }}>
          <Clock size={14} />
          <span>{task.deadline_days}d</span>
        </div>
      </div>

      <div style={{ marginTop: '1rem', display: 'flex', gap: '0.5rem' }}>
        {task.status !== 'To Do' && (
          <button onClick={(e) => handleStatusChange(e, 'To Do')} style={{ fontSize: '0.75rem', padding: '2px 6px', background: '#f4f5f7', border: '1px solid #dfe1e6', borderRadius: '3px', cursor: 'pointer' }}>To Do</button>
        )}
        {task.status !== 'In Progress' && (
          <button onClick={(e) => handleStatusChange(e, 'In Progress')} style={{ fontSize: '0.75rem', padding: '2px 6px', background: '#f4f5f7', border: '1px solid #dfe1e6', borderRadius: '3px', cursor: 'pointer' }}>In Progress</button>
        )}
        {task.status !== 'Done' && (
          <button onClick={(e) => handleStatusChange(e, 'Done')} style={{ fontSize: '0.75rem', padding: '2px 6px', background: '#f4f5f7', border: '1px solid #dfe1e6', borderRadius: '3px', cursor: 'pointer' }}>Done</button>
        )}
      </div>
    </div>

    {/* Detailed Task Modal */}
    {showDetails && (
      <div style={{ position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', background: 'rgba(9, 30, 66, 0.5)', backdropFilter: 'blur(4px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: '1rem' }}>
        <div className="card animate-scale-in" style={{ width: '100%', maxWidth: '700px', maxHeight: '90vh', display: 'flex', flexDirection: 'column', padding: '0', overflow: 'hidden' }}>
          
          {/* Modal Header */}
          <div style={{ padding: '1.5rem', borderBottom: '1px solid #dfe1e6', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', background: '#f8f9fa' }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
                <span style={{ fontSize: '0.75rem', fontWeight: 700, padding: '2px 8px', borderRadius: '12px', background: task.status === 'Done' ? '#e3fcef' : task.status === 'In Progress' ? '#deebff' : '#ebecf0', color: task.status === 'Done' ? '#006644' : task.status === 'In Progress' ? '#0052cc' : '#5e6c84', textTransform: 'uppercase' }}>
                  {task.status}
                </span>
                <span style={{ fontSize: '0.75rem', color: '#5e6c84' }}>Task #{task.id?.substring ? task.id.substring(0,6) : task.id}</span>
              </div>
              <h2 style={{ fontSize: '1.25rem', fontWeight: 600, color: '#172b4d', margin: 0 }}>{task.title}</h2>
            </div>
            <button onClick={() => setShowDetails(false)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#5e6c84', padding: '0.25rem' }}><X size={24} /></button>
          </div>
          
          {/* Modal Scrollable Content */}
          <div style={{ padding: '1.5rem', overflowY: 'auto' }}>
            
            <div style={{ marginBottom: '1.5rem' }}>
              <h4 style={{ fontSize: '0.85rem', fontWeight: 600, color: '#5e6c84', marginBottom: '0.5rem', textTransform: 'uppercase' }}>Full Description</h4>
              <div style={{ fontSize: '0.9rem', color: '#172b4d', lineHeight: '1.6', whiteSpace: 'pre-wrap', background: '#f4f5f7', padding: '1rem', borderRadius: '8px', border: '1px solid #dfe1e6' }}>
                {task.description || 'No detailed description provided.'}
              </div>
            </div>

            {/* GitHub CI/CD Integration Section */}
            <div style={{ marginBottom: '2rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
                <GitMerge size={18} color="#172b4d" />
                <h4 style={{ fontSize: '0.85rem', fontWeight: 600, color: '#172b4d', margin: 0, textTransform: 'uppercase' }}>CI/CD Pipeline Status</h4>
              </div>
              
              <div style={{ padding: '1.25rem', border: '1px solid #dfe1e6', borderRadius: '8px', background: '#ffffff', boxShadow: '0 1px 2px rgba(0,0,0,0.03)' }}>
                {task.status === 'To Do' ? (
                  <div style={{ textAlign: 'center', color: '#5e6c84', padding: '1rem 0' }}>
                    <GitBranch size={32} color="#c1c7d0" style={{ marginBottom: '0.5rem' }} />
                    <p style={{ margin: 0, fontSize: '0.9rem' }}>No active branches or pull requests yet.</p>
                    <p style={{ margin: '0.25rem 0 0 0', fontSize: '0.8rem' }}>Move task to "In Progress" to initiate CI/CD tracking.</p>
                  </div>
                ) : (
                  <>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', marginBottom: '1.5rem' }}>
                      {loadingGithub ? (
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', color: '#5e6c84', padding: '1rem' }}>
                          <Loader2 size={16} className="animate-spin" />
                          <span style={{ fontSize: '0.85rem' }}>Fetching live GitHub stream...</span>
                        </div>
                      ) : githubCommits.length > 0 ? (
                        githubCommits.map((commit, idx) => (
                          <div key={idx} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                            <div>
                              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.25rem' }}>
                                <GitBranch size={14} color="#0052cc" />
                                <span style={{ fontSize: '0.85rem', fontWeight: 600, color: '#0052cc' }}>main</span>
                                <span style={{ fontSize: '0.8rem', color: '#5e6c84', fontFamily: 'monospace', background: '#f4f5f7', padding: '2px 4px', borderRadius: '4px' }}>{commit.sha}</span>
                              </div>
                              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                <GitCommit size={14} color="#5e6c84" />
                                <span style={{ fontSize: '0.85rem', color: '#172b4d', fontWeight: 500 }}>{commit.message}</span>
                              </div>
                              <div style={{ fontSize: '0.75rem', color: '#5e6c84', marginLeft: '1.25rem', marginTop: '0.15rem' }}>
                                by {commit.author} • {new Date(commit.date).toLocaleDateString()}
                              </div>
                            </div>
                            {idx === 0 && (
                              <div style={{ background: '#e3fcef', color: '#006644', padding: '4px 10px', borderRadius: '16px', fontSize: '0.75rem', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                                <CheckCircle size={12} /> LATEST
                              </div>
                            )}
                          </div>
                        ))
                      ) : (
                        <div style={{ textAlign: 'center', padding: '1rem', color: '#5e6c84' }}>No real commit data found for this context.</div>
                      )}
                    </div>

                    {/* Visual Pipeline */}
                    <div style={{ position: 'relative', display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0 1rem' }}>
                      <div style={{ position: 'absolute', top: '50%', left: '2rem', right: '2rem', height: '2px', background: '#dfe1e6', zIndex: 0, transform: 'translateY(-50%)' }}></div>
                      
                      {/* Step 1: Build */}
                      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.5rem', zIndex: 1, background: '#fff', padding: '0 0.5rem' }}>
                        {task.status === 'Done' || task.status === 'In Progress' ? <CheckCircle size={24} color="#00875a" fill="#e3fcef" /> : <Circle size={24} color="#c1c7d0" fill="#fff" />}
                        <span style={{ fontSize: '0.75rem', fontWeight: 600, color: task.status === 'To Do' ? '#c1c7d0' : '#172b4d' }}>Build</span>
                        <span style={{ fontSize: '0.65rem', color: '#5e6c84' }}>{task.status !== 'To Do' ? '1m 12s' : '-'}</span>
                      </div>

                      {/* Step 2: Test */}
                      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.5rem', zIndex: 1, background: '#fff', padding: '0 0.5rem' }}>
                        {task.status === 'Done' ? <CheckCircle size={24} color="#00875a" fill="#e3fcef" /> : task.status === 'In Progress' ? <Loader2 size={24} color="#0052cc" className="animate-spin" /> : <Circle size={24} color="#c1c7d0" fill="#fff" />}
                        <span style={{ fontSize: '0.75rem', fontWeight: 600, color: task.status === 'Done' || task.status === 'In Progress' ? '#172b4d' : '#c1c7d0' }}>Tests & QA</span>
                        <span style={{ fontSize: '0.65rem', color: '#5e6c84' }}>{task.status === 'Done' ? '2m 45s' : task.status === 'In Progress' ? 'Running...' : '-'}</span>
                      </div>

                      {/* Step 3: Deploy */}
                      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.5rem', zIndex: 1, background: '#fff', padding: '0 0.5rem' }}>
                        {task.status === 'Done' ? <CheckCircle size={24} color="#00875a" fill="#e3fcef" /> : <Circle size={24} color="#c1c7d0" fill="#fff" />}
                        <span style={{ fontSize: '0.75rem', fontWeight: 600, color: task.status === 'Done' ? '#172b4d' : '#c1c7d0' }}>Deploy</span>
                        <span style={{ fontSize: '0.65rem', color: '#5e6c84' }}>{task.status === 'Done' ? 'Production' : 'Pending'}</span>
                      </div>
                    </div>
                  </>
                )}
              </div>
            </div>

            <div style={{ marginBottom: '1rem' }}>
              <h4 style={{ fontSize: '0.85rem', fontWeight: 600, color: '#5e6c84', marginBottom: '1rem', textTransform: 'uppercase' }}>Team Progress & Allocation</h4>
              
              {/* Derived/Mocked Team Progress Data */}
              {[
                { name: task.assignee && task.assignee !== 'Unassigned' ? task.assignee : 'Team Lead', role: 'Primary Assignee', progress: task.status === 'Done' ? 100 : task.status === 'In Progress' ? 65 : 0, color: '#0052cc' },
                { name: 'Architecture Review', role: 'System Reliability', progress: task.status === 'Done' ? 100 : task.status === 'In Progress' ? 40 : 0, color: '#ffab00' }
              ].map((member, i) => (
                <div key={i} style={{ marginBottom: '0.75rem', padding: '1rem', border: '1px solid #dfe1e6', borderRadius: '8px', background: '#ffffff', boxShadow: '0 1px 2px rgba(0,0,0,0.03)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                      <div style={{ width: '32px', height: '32px', borderRadius: '50%', background: `${member.color}20`, color: member.color, display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 600, fontSize: '0.85rem' }}>
                        {member.name.charAt(0)}
                      </div>
                      <div>
                        <div style={{ fontWeight: 600, fontSize: '0.9rem', color: '#172b4d' }}>{member.name}</div>
                        <div style={{ fontSize: '0.75rem', color: '#5e6c84' }}>{member.role}</div>
                      </div>
                    </div>
                    <div style={{ fontWeight: 700, fontSize: '1rem', color: member.color }}>{member.progress}%</div>
                  </div>
                  <div style={{ width: '100%', height: '6px', background: '#ebecf0', borderRadius: '3px', overflow: 'hidden', marginTop: '0.5rem' }}>
                    <div style={{ width: `${member.progress}%`, height: '100%', background: member.color, borderRadius: '3px', transition: 'width 1s ease-out' }}></div>
                  </div>
                </div>
              ))}
            </div>

            {/* Generate Report Button */}
            <div style={{ marginTop: '2rem', display: 'flex', justifyContent: 'center' }}>
              <button 
                onClick={handleDownloadReport}
                style={{ 
                  display: 'flex', 
                  alignItems: 'center', 
                  gap: '0.5rem', 
                  background: '#172b4d', 
                  color: 'white', 
                  border: 'none', 
                  borderRadius: '6px', 
                  padding: '0.75rem 1.5rem', 
                  fontWeight: 600, 
                  cursor: 'pointer',
                  transition: 'background 0.2s',
                  boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
                }}
                onMouseOver={(e) => e.currentTarget.style.background = '#091e42'}
                onMouseOut={(e) => e.currentTarget.style.background = '#172b4d'}
              >
                <FileText size={18} />
                Download Flow Report
              </button>
            </div>

          </div>
        </div>
      </div>
    )}
    </>
  );
};

export default TaskCard;

