import React, { useState, useEffect } from 'react';
import { Clock, User, AlertCircle, X, GitMerge, GitBranch, GitCommit, Loader2, FileText, CheckCircle, Circle } from 'lucide-react';
import GlassCard from './GlassCard';
import { motion, AnimatePresence } from 'framer-motion';

const TaskCard = ({ task, onStatusChange }) => {
  const [showDetails, setShowDetails] = useState(false);

  const getRiskColorClass = (score) => {
    if (score > 70) return 'border-l-rose-500 hover:shadow-[0_0_15px_rgba(244,63,94,0.15)]'; // High Risk
    if (score > 40) return 'border-l-amber-500 hover:shadow-[0_0_15px_rgba(245,158,11,0.15)]'; // Medium Risk
    return 'border-l-cyan-500 hover:shadow-[0_0_15px_rgba(6,182,212,0.15)]'; // Low Risk
  };

  const getRiskTextColor = (score) => {
    if (score > 70) return 'text-rose-400 bg-rose-950/20 border-rose-900/30';
    if (score > 40) return 'text-amber-400 bg-amber-950/20 border-amber-900/30';
    return 'text-cyan-400 bg-cyan-950/20 border-cyan-900/30';
  };

  // Helper to stop propagation for inline buttons
  const [githubCommits, setGithubCommits] = useState([]);
  const [loadingGithub, setLoadingGithub] = useState(false);

  useEffect(() => {
    if (showDetails && task.status !== 'To Do') {
      const fetchCommits = async () => {
        setLoadingGithub(true);
        try {
          const res = await fetch(`http://localhost:5000/api/github/commits?repo=facebook/react`);
          const data = await res.json();
          if (data.status === 'success') {
            setGithubCommits(data.commits);
          }
        } catch (err) { console.error(err); }
        setLoadingGithub(false);
      };
      fetchCommits();
    }
  }, [showDetails, task.status]);

  const handleStatusChange = (e, status) => {
    e.stopPropagation();
    onStatusChange(task.id, status);
  };

  const handleDownloadReport = () => {
    const reportContent = `
========================================
       AI TASK FLOW REPORT
========================================
Task ID: ${task.id}
Title: ${task.title}
Status: ${task.status}
Risk: ${task.risk_score > 70 ? 'High' : task.risk_score > 40 ? 'Medium' : 'Low'} (${task.risk_score}%)
Assignee: ${task.assignee || 'Unassigned'}
Deadline: ${task.deadline_days} days

--- DESCRIPTION ---
${task.description || 'No detailed description provided.'}

--- CI/CD PIPELINE STATUS ---
${task.status === 'Done' ? 'Deployed to Production successfully.' : task.status === 'In Progress' ? 'Currently Pipeline is running (Tests & QA in progress).' : 'No active branches.'}

--- TEAM ALLOCATION ---
Primary Assignee: ${task.assignee || 'Team Lead'} (${task.status === 'Done' ? '100' : task.status === 'In Progress' ? '65' : '0'}%)
System Review: Architecture Team (${task.status === 'Done' ? '100' : task.status === 'In Progress' ? '40' : '0'}%)

Generated by NexaAI Decision Intelligence
========================================
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Task_Flow_Report_${task.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <>
    <div
      onClick={() => setShowDetails(true)}
      className={`glass-panel p-4 mb-3 border-l-4 cursor-pointer transition-all duration-300 hover:-translate-y-0.5 border border-white/5 bg-white/[0.01] hover:bg-white/[0.02] ${getRiskColorClass(task.risk_score)}`}
    >
      <div className="flex justify-between items-start gap-2 mb-2">
        <h4 className="font-bold text-white text-xs leading-snug line-clamp-2">{task.title}</h4>
        <div className={`text-[8px] font-mono font-bold uppercase tracking-wider px-2 py-0.5 rounded border shrink-0 flex items-center gap-1 ${getRiskTextColor(task.risk_score)}`}>
          <AlertCircle size={8} />
          {task.risk_score > 70 ? 'High Risk' : task.risk_score > 40 ? 'Med Risk' : 'Low Risk'}
        </div>
      </div>
      
      <p className="text-[11px] text-slate-400 leading-relaxed line-clamp-2 mb-4 font-sans">
        {task.description || 'No description provided.'}
      </p>

      <div className="flex justify-between items-center text-[10px] text-slate-500 font-mono">
        <div className="flex items-center gap-1">
          <User size={12} className="text-slate-500" />
          <span>{task.assignee || 'Unassigned'}</span>
        </div>
        <div className="flex items-center gap-1">
          <Clock size={12} className="text-slate-500" />
          <span>{task.deadline_days}d</span>
        </div>
      </div>

      {/* Action States */}
      <div className="mt-3.5 pt-3 border-t border-white/5 flex gap-1.5 flex-wrap">
        {task.status !== 'To Do' && (
          <button 
            onClick={(e) => handleStatusChange(e, 'To Do')} 
            className="text-[9px] font-mono px-2 py-0.5 rounded bg-white/[0.02] hover:bg-white/[0.06] border border-white/5 hover:border-white/10 text-slate-400 hover:text-white cursor-pointer transition-colors"
          >
            TO DO
          </button>
        )}
        {task.status !== 'In Progress' && (
          <button 
            onClick={(e) => handleStatusChange(e, 'In Progress')} 
            className="text-[9px] font-mono px-2 py-0.5 rounded bg-white/[0.02] hover:bg-white/[0.06] border border-white/5 hover:border-white/10 text-slate-400 hover:text-white cursor-pointer transition-colors"
          >
            IN PROGRESS
          </button>
        )}
        {task.status !== 'Done' && (
          <button 
            onClick={(e) => handleStatusChange(e, 'Done')} 
            className="text-[9px] font-mono px-2 py-0.5 rounded bg-white/[0.02] hover:bg-white/[0.06] border border-white/5 hover:border-white/10 text-slate-400 hover:text-white cursor-pointer transition-colors"
          >
            DONE
          </button>
        )}
      </div>
    </div>

    {/* Detailed Task Modal */}
    <AnimatePresence>
      {showDetails && (
        <div className="fixed inset-0 bg-black/75 backdrop-blur-md z-[1200] flex items-center justify-center p-4">
          <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            className="glass-panel-heavy rounded-2xl w-full max-w-[640px] max-h-[90vh] flex flex-col p-0 overflow-hidden border border-white/10 shadow-2xl"
          >
            
            {/* Modal Header */}
            <div className="p-5 border-b border-white/5 flex justify-between items-start bg-white/[0.01]">
              <div>
                <div className="flex items-center gap-2 mb-1.5">
                  <span className={`text-[9px] font-mono font-bold px-2 py-0.5 rounded border uppercase tracking-wider ${
                    task.status === 'Done' 
                      ? 'bg-emerald-950/20 border-emerald-900/30 text-emerald-400' 
                      : task.status === 'In Progress' 
                        ? 'bg-neon-purple/20 border-neon-purple/30 text-neon-purple' 
                        : 'bg-white/[0.02] border-white/10 text-slate-400'
                  }`}>
                    {task.status}
                  </span>
                  <span className="text-[10px] text-slate-500 font-mono">TASK #{task.id?.substring ? task.id.substring(0,6) : task.id}</span>
                </div>
                <h2 className="text-sm font-bold text-white tracking-wide leading-tight">{task.title}</h2>
              </div>
              <button onClick={() => setShowDetails(false)} className="text-slate-400 hover:text-white p-1 hover:bg-white/5 rounded-lg transition-colors cursor-pointer">
                <X size={18} />
              </button>
            </div>
            
            {/* Modal Content */}
            <div className="p-5 overflow-y-auto space-y-5">
              
              {/* Description */}
              <div className="space-y-2">
                <h4 className="text-[9px] font-bold text-slate-500 uppercase tracking-widest">Full Description</h4>
                <div className="text-xs text-slate-300 leading-relaxed font-sans bg-black/45 p-4 rounded-xl border border-white/5 whitespace-pre-wrap">
                  {task.description || 'No detailed description provided.'}
                </div>
              </div>

              {/* GitHub CI/CD Integration */}
              <div className="space-y-3">
                <div className="flex items-center gap-1.5">
                  <GitMerge size={16} className="text-neon-cyan" />
                  <h4 className="text-[9px] font-bold text-slate-300 uppercase tracking-widest">CI/CD Pipeline Tracking</h4>
                </div>
                
                <div className="p-4 border border-white/5 rounded-xl bg-black/30 space-y-4">
                  {task.status === 'To Do' ? (
                    <div className="text-center py-6 text-slate-500">
                      <GitBranch size={28} className="mx-auto mb-2 text-slate-600" />
                      <p className="text-xs">No active branches or commits located.</p>
                      <p className="text-[10px] text-slate-600 font-mono mt-0.5">MOVE TASK TO IN PROGRESS TO TRACK REPOSITORIES</p>
                    </div>
                  ) : (
                    <>
                      {/* Commits List */}
                      <div className="space-y-3">
                        {loadingGithub ? (
                          <div className="flex items-center gap-2 text-slate-500 text-xs py-2">
                            <Loader2 size={14} className="animate-spin text-neon-purple" />
                            <span>Interrogating GitHub API Stream...</span>
                          </div>
                        ) : githubCommits.length > 0 ? (
                          githubCommits.slice(0, 2).map((commit, idx) => (
                            <div key={idx} className="flex justify-between items-center text-xs">
                              <div>
                                <div className="flex items-center gap-2 mb-1">
                                  <GitBranch size={12} className="text-neon-purple" />
                                  <span className="font-semibold text-white">main</span>
                                  <span className="text-[10px] text-slate-400 font-mono bg-white/[0.04] px-1.5 py-0.5 rounded border border-white/5">{commit.sha}</span>
                                </div>
                                <div className="flex items-center gap-2">
                                  <GitCommit size={12} className="text-slate-500" />
                                  <span className="text-slate-300">{commit.message}</span>
                                </div>
                                <div className="text-[9px] text-slate-500 font-mono mt-1">
                                  Operator: {commit.author} • {new Date(commit.date).toLocaleDateString()}
                                </div>
                              </div>
                              {idx === 0 && (
                                <div className="bg-emerald-950/20 border border-emerald-900/30 text-emerald-400 px-2 py-0.5 rounded-full text-[9px] font-mono font-bold flex items-center gap-1 uppercase tracking-wider shrink-0">
                                  <CheckCircle size={10} /> Latest
                                </div>
                              )}
                            </div>
                          ))
                        ) : (
                          <div className="text-center text-slate-500 text-xs">No active commits found.</div>
                        )}
                      </div>

                      {/* Timeline flow */}
                      <div className="relative flex justify-between items-center px-4 pt-2">
                        <div className="absolute top-1/2 left-8 right-8 h-[1px] bg-white/5 z-0 -translate-y-1/2"></div>
                        
                        {/* Build Step */}
                        <div className="flex flex-col items-center gap-1.5 z-10 bg-black/45 px-2 py-1 rounded border border-white/5">
                          {task.status === 'Done' || task.status === 'In Progress' ? <CheckCircle size={18} className="text-emerald-400" /> : <Circle size={18} className="text-slate-600" />}
                          <span className="text-[9px] font-semibold text-slate-400 font-mono">BUILD</span>
                          <span className="text-[8px] text-slate-600 font-mono">{task.status !== 'To Do' ? '1m 12s' : '-'}</span>
                        </div>

                        {/* Test Step */}
                        <div className="flex flex-col items-center gap-1.5 z-10 bg-black/45 px-2 py-1 rounded border border-white/5">
                          {task.status === 'Done' ? <CheckCircle size={18} className="text-emerald-400" /> : task.status === 'In Progress' ? <Loader2 size={18} className="text-neon-purple animate-spin" /> : <Circle size={18} className="text-slate-600" />}
                          <span className="text-[9px] font-semibold text-slate-400 font-mono">TESTS & QA</span>
                          <span className="text-[8px] text-slate-600 font-mono">{task.status === 'Done' ? '2m 45s' : task.status === 'In Progress' ? 'Running' : '-'}</span>
                        </div>

                        {/* Deploy Step */}
                        <div className="flex flex-col items-center gap-1.5 z-10 bg-black/45 px-2 py-1 rounded border border-white/5">
                          {task.status === 'Done' ? <CheckCircle size={18} className="text-emerald-400" /> : <Circle size={18} className="text-slate-600" />}
                          <span className="text-[9px] font-semibold text-slate-400 font-mono">DEPLOY</span>
                          <span className="text-[8px] text-slate-600 font-mono">{task.status === 'Done' ? 'Production' : 'Pending'}</span>
                        </div>
                      </div>
                    </>
                  )}
                </div>
              </div>

              {/* Allocations progress */}
              <div className="space-y-3">
                <h4 className="text-[9px] font-bold text-slate-500 uppercase tracking-widest">Ownership & Operational Coverage</h4>
                <div className="space-y-2">
                  {[
                    { name: task.assignee && task.assignee !== 'Unassigned' ? task.assignee : 'Team Lead', role: 'Primary Assignee', progress: task.status === 'Done' ? 100 : task.status === 'In Progress' ? 65 : 0, color: 'text-neon-purple', bar: 'bg-neon-purple' },
                    { name: 'Architecture Review Board', role: 'System Security Validation', progress: task.status === 'Done' ? 100 : task.status === 'In Progress' ? 40 : 0, color: 'text-neon-cyan', bar: 'bg-neon-cyan' }
                  ].map((member, i) => (
                    <div key={i} className="p-3 border border-white/5 rounded-xl bg-black/25 flex items-center justify-between gap-4">
                      <div className="flex items-center gap-3">
                        <div className={`w-8 h-8 rounded-lg bg-white/[0.02] border border-white/5 flex items-center justify-center font-mono font-bold text-xs ${member.color}`}>
                          {member.name.charAt(0)}
                        </div>
                        <div>
                          <div className="text-xs font-semibold text-white">{member.name}</div>
                          <div className="text-[10px] text-slate-500">{member.role}</div>
                        </div>
                      </div>
                      <div className="text-right shrink-0">
                        <div className={`text-xs font-bold font-mono ${member.color}`}>{member.progress}%</div>
                        <div className="w-20 h-1 bg-white/[0.04] rounded-full overflow-hidden mt-1">
                          <div className={`h-full rounded-full ${member.bar}`} style={{ width: `${member.progress}%` }}></div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Generate Report */}
              <div className="pt-4 flex justify-center border-t border-white/5">
                <button 
                  onClick={handleDownloadReport}
                  className="bg-neon-purple hover:bg-neon-purple/80 text-white font-bold text-xs py-2.5 px-6 rounded-xl cursor-pointer shadow-[0_0_15px_rgba(168,85,247,0.2)] transition-all duration-200 flex items-center gap-2 uppercase tracking-wider font-mono"
                >
                  <FileText size={14} />
                  Download Flow Report
                </button>
              </div>

            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
    </>
  );
};

export default TaskCard;
